### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by polytheistic** [tuxity/insta-unfollower#36] opened 2020-05-19 18:22 UTC
C:\Users\HEATHEN\Desktop\insta-unfollower-master>py insta-unfollower.py INSTA_USERNAME=no INSTA_PASSWORD=no python3 insta-unfollower.py
Traceback (most recent call last):
  File "insta-unfollower.py", line 288, in <module>
    main()
  File "insta-unfollower.py", line 213, in main
    is_logged = login()
  File "insta-unfollower.py", line 63, in login
    response_data = json.loads(response.text)
  File "D:\Program Files\Python\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Program Files\Python\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Program Files\Python\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by h5p9sl** [comment] 2020-05-21 06:34
Duplicate of #35
The error is caused by response.text being equal to 'Bad response', causing json parsing errors.

**Comment by eduardobarbiero** [comment] 2020-07-24 14:58
try see:

https://github.com/tuxity/insta-unfollower/pull/38/commits/06121d099d98ce696e959ffe83c93fac851ac3d9

**Comment by tuxity** [comment] 2021-02-03 10:44
Hello,

It should be fixed since a while now. I'm closing the issue, don't hesitate to comment if needed.

**Closed by tuxity** 2021-02-03 10:44 UTC
